openapi: '3.0.0'
info:
  version: '1'
  title: Custom Validator Example
servers:
  - url: http://localhost:8080/{basePath}
    variables:
      basePath:
        default: api
paths:
  /echo:
    post:
      operationId: oneof.echo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                foo:
                  oneOf:
                    - {type: boolean}
                    - {type: number}
      responses:
        '200':
          description: Echo the validated request.
