openapi: "3.0.0"

info:
  title: Big request handler
  version: "1.0"
servers:
  - url: http://localhost:8080/api

paths:
  /:
    post:
      summary: Compute string length
      operationId: server.length
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        200:
          description: Length of the string
          content:
            application/json:
              schema:
                type: integer
                example: 15
